const slides = [
    { src: "/public/flyers/1T1.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/Angie's Beauty Palour_flyer_001.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/Angie's Beauty Palour_flyer_002.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/chocolate-smoothie-final.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/church-poster-2 copy.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/codeschool-2.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/codeschool-3-1.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/codeschool.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/CPC-realtor-flyer-2-2.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/CPC-realtor-flyer-3-2.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/disc.mat.master.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/disc.mat.more.copy.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/gracias-graduation-party copy.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/khumbo-bio-final.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/living'i poster_001-1.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/makario-singles-.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/mama-kachikuwa-birthday.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/mama_chri_chri.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/mama_chri_chri_pricelist.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/mom-retirement-party.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/moot-court-flyer.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/nkhuku-final.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/nthano-IT-shulushulu copy.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ostritch-pictures-0-1.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ostritch-pictures-1-2.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/public-lecture-final.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/RITZ-FINAL-ROUND.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ritz-pre-moot-training.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ritz-round-1-V3.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ritz-second-round-1@3x.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/ritz-starting-soon-.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/shoe_flyer1.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/Thando.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/US.embassy.jpg", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/flyers/vie-cakes-flyer-4.jpg", title: "", description: "", width: 1080, height: 1080 }
];
