const slides = [
    { src: "/public/logos/3x.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/amalawi-anzanga.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/angie-beauty-parlour.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/angie-wigs.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/ariaz-phala.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/blackspider.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/emtiquemedia.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/firm-and-strong.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/iMORRCS.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/let-love-lead.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/localman-main.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/localman-sub-1.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/localman-sub-2.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/malu-the-comedian.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/omikhe-1.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/omikhe-2.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/streamlycs.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/sweet-grill.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/tchaman-main.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/tchanman-sub.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/valuations-africa.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/wizbago.png", title: "", description: "", width: 1080, height: 1080 },
    { src: "/public/logos/ziyembe-community-radio.png", title: "", description: "", width: 1080, height: 1080 }
];
